[package]
name = "test-app-b"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "test_duplicate_app"
path = "src/bin/test_duplicate_app.rs"

[dependencies]
bevy = { workspace = true }
bevy_brp_extras = { workspace = true }